version: "3.9"
services:
  nginxl4:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./tcp.cfg:/etc/nginx/nginx.conf:ro

  nginxl7:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - ./ws.cfg:/etc/nginx/nginx.conf:ro

  server1:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "run", "server.go"]
    ports:
      - "8080:8080"
    environment:
      - APPID=8080

  server2:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "run", "server.go"]
    ports:
      - "8081:8080"
    environment:
      - APPID=8081

  server3:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "run", "server.go"]
    ports:
      - "8082:8080"
    environment:
      - APPID=8082